### ISSUE TITLE
Not Found error

### ISSUE THREAD

**Issue by allnnde** [joutvhu/get-release#85]
hi, i have a problem,  i try to use this action for get last releases for mi another repos, but every return Not Found error.
the another repository should bu public?

sorry for my english
Thx

**Comment by joutvhu** [comment]
You need a token to access private repository

First of all, you need to access https://github.com/settings/personal-access-tokens/new to generate a new token

- In the `Repository access` section, select `All repositories` or `Only select repositories` then select the repo you want to get release info
- In the `Repository permissions` section, select `Read-only` or `Read and write` for `Contents` permission
- Click `Generate token` then copy token

Use the generated token for the `GITHUB_TOKEN` environment variable in the `get-release` action
